### ISSUE TITLE
Add BlueSky

### ISSUE THREAD

**Issue by ivastar** [xuanxu/acceptance-tweet-action#2]
There is a somewhat lively group of astro folks on Blue Sky, would be nice to have a "post on bsky.app" at acceptance. JOSS does not have an account there.

**Comment by xuanxu** [comment]
Definitely on my list, I have to play with the API to see how easy it would be

**Comment by xuanxu** [comment]
It's working! https://bsky.app/profile/joss-openjournals.bsky.social/post/3l6gac6bsfs2i
